#!/usr/bin/env ruby

require_relative "../init"

require "component_host"

ComponentHost.start("invalid-argument-error-test-component") do |host|
  host.register(InvalidArgumentErrorTestComponent::Start)
end
